### ISSUE TITLE
CDT token in untrusted

### ISSUE THREAD

**Issue by alonmuroch** [balancer-labs/assets#28]
Hi @Destiner @rabmarut @mikemcdonald @bonustrack I've noticed the token CDT at address 0x177d39AC676ED1C67A2b268AD7F1E58826E5B0af is in you untrusted list, not really sure why. 
Could you please remove it? people can't create a pool for it.

**Comment by Destiner** [comment]
This token doesn't return bool value on `transfer` and therefore is not a ERC20-compatible token. It will not work with Balancer protocol.
